package onBoard.network.networkUtils;

import java.io.Serializable;

/*
    The RequestToken class is responsible for storing requests.
 */
public class RequestToken implements Serializable {
    // The requestFor string determines what type of request this is.
    public String requestFor;

    // The authentication object is used as supplemental data determining
    // the validity of this request.
    public Object authentication;

    // The response object is sent by the server as a response to the request.
    // In this project, this can be boolean for authentication or
    // a quiz object for a quiz response.
    public Object response = null;

    // The signature is automatically generated by the PortHandler class, and
    // tells the server what port the client is listening to when waiting
    // for a response token.
    public int signature;

    // The exception object is responsible for holding exceptions whenever an
    // error occurs. It should be that the exception should be null
    // if no error has occurred.
    public Object exception = null;

    public RequestToken (){}

    public RequestToken (String requestFor, Object authentication, int signature) {
        this.authentication = authentication;
        this.requestFor = requestFor;
        this.signature = signature;
    }

    public RequestToken (String requestFor, Object authentication) {
        this.authentication = authentication;
        this.requestFor = requestFor;
    }

    @Override
    public String toString() {
        return "RequestToken{" +
                "\nrequestFor='" + requestFor + '\'' +
                "\nauthentication=" + authentication.toString() +
                "\nresponse=" + response +
                "\nsignature=" + signature +
                "\nexception=" + exception +
                "\n}";
    }
}
