package Network;

import QuizQuestions.Quiz;

import javax.sound.sampled.Port;
import java.io.Serializable;

/*
    The RequestToken class is responsible for storing requests.
 */
public class RequestToken implements Serializable {
    // The requestFor string determines what type of request this is.
    public String requestFor;

    // The authentication object is used as supplemental data determining
    // the validity of this request.
    public Object authentication;

    // The response object is sent by the server as a response to the request.
    // In this project, this can be boolean for authentication or
    // a quiz object for a quiz response.
    public Object response = null;

    // The signature is automatically generated by the PortHandler class, and
    // tells the server what port the client is listening to when waiting
    // for a response token.
    public int signature;

    public RequestToken (){}

    public RequestToken (String requestFor, Object authentication, int signature) {
        this.authentication = authentication;
        this.requestFor = requestFor;
        this.signature = signature;
    }

    public RequestToken (String requestFor, Object authentication) {
        this.authentication = authentication;
        this.requestFor = requestFor;
    }



}
